### PR TITLE
Update to 6.5 kernel with latest AMD SEV-SNP and SVSM required patches

### PR DESCRIPTION
**Pull request by roy-hopkins**
This PR is a refresh of the current coconut SVSM branch which includes the current patch sets to support SEV-SNP, FD guest private memory, host and guest SVSM support.

The kernel tree is based on AMD's preview SVSM host support branch: https://github.com/AMDESE/linux/tree/svsm-preview-hv-v3. This branch contains:
* The latest guest_memfd patchset with the exception of a couple of FIXUP commits. 
* SNP patches from https://github.com/AMDESE/linux/tree/snp-host-latest
* Host SVSM support patches

This was then rebased on 6.5 upstream and the AMD SVSM guest changes were cherry picked from https://github.com/AMDESE/linux/commits/svsm-preview-guest-v3.

The resulting kernel built from this tree can be used both on the host system on a system that supports AMD SEV-SNP, and on guests running at VMPL-1 with coconut SVSM.

The current coconut QEMU needs to be updated to work with this kernel. A separate PR will be raised on the coconut QEMU repo to support this.

### CODE REVIEW

**Comment by crobinso** [comment]
Just trying a build test, on fedora 39 host, I needed to cherry-pick these two upstream commits to get things building without errors.

```
commit d66ba6dc1cce914673bd8a89fca30a7715ea70d1
Author: Cédric Le Goater <clg@redhat.com>
Date:   Thu Apr 20 22:29:39 2023 +0200

    async: Suppress GCC13 false positive in aio_bh_poll()
```

```
commit a4680b8de3ec2a16afa55a5415ca0143ef4ec027
Author: Peter Maydell <peter.maydell@linaro.org>
Date:   Tue Jun 20 17:20:24 2023 +0100

    pc-bios/keymaps: Use the official xkb name for Arabic layout, not the legacy synonym
```

**Comment by crobinso** [comment]
Using this as host kernel, plus the qemu branch, my existing SVSM VM booted fine. I didn't try it as guest kernel yet

**Comment by roy-hopkins** [comment]
> Using this as host kernel, plus the qemu branch, my existing SVSM VM booted fine. I didn't try it as guest kernel yet

That's great to know. Thanks for testing.

**Comment by joergroedel** [comment]
So I tested this and it works great. Biggest benefit so far is that we get support for unaccepted memory with the new kernel, which really improves boot times!

For the guest kernel I had some compile issues to fix, mainly because guest support required to also build host support into the kernel. This are probably issues introduced with the SNP host patches.

**Comment by roy-hopkins** [comment]
> So I tested this and it works great. Biggest benefit so far is that we get support for unaccepted memory with the new kernel, which really improves boot times!

I noticed that SVSM takes longer to run through the start of the kernel as it accepts memory at runtime but in general, yes it seems faster.

> For the guest kernel I had some compile issues to fix, mainly because guest support required to also build host support into the kernel. This are probably issues introduced with the SNP host patches.

Interesting. What were the compile issues? I used the same kernel config for both host and guest with no build or runtime issues.

**Comment by joergroedel** [comment]
> Interesting. What were the compile issues? I used the same kernel config for both host and guest with no build or runtime issues.

I had a minimal config for the guest, will send it to you tomorrow.

**Comment by roy-hopkins** [comment]
Amended commits to fix build errors when CONFIG_KVM_AMD_SEV is not configured.

8abf6932b5a9287ef0b3b0c18d594ace0d1261df
4687b3abc4dc28e08c99b45ba901f50daced5b66

**Comment by joergroedel** [comment]
Pushed these changes into the svsm branch, thanks!

**Pull request closed without merging**
